### PR TITLE
Create, update, delete events

### PR DESCRIPTION
**Pull request by calebhaye**

### CODE REVIEW

**Comment by zyphlar** [comment]
FYI @calebhaye I know travisci is being stupid right now but I ran the test suite on my laptop after deleting/recreating the images and getting the volumes/npminstall right. Here's what I got:

```
Failed tests:

  5) DELETE /events/ should successfully delete an event:

      actual ~~expected~~

      500~~200~~

      Expected 500 to equal specified value: 200

      at /home/app/test/routes/events/delete.js:47:31

  6) POST /user should create a user:

      actual ~~expected~~

      422~~200~~

      Expected 422 to equal specified value: 200

      at /home/app/test/routes/users/add.js:49:31


2 of 19 tests failed (3 skipped)
Test duration: 946 ms

```

**Comment by calebhaye** [comment]
@zyphlar The latest commit fixes the test for events. 

Unfortunately, the create user test is still failing.  I believe it's failing because the delete event test (`events/delete.js`) uses a fixture (`users`) that the `users/add.js` assumes it will be initializing for its create user test. 🙄

**Comment by calebhaye** [comment]
Travis is crazy.  Not sure wth is going on there, but yes it's entirely borked.

**Comment by calebhaye** [comment]
@zyphlar commit 42ac2cc fixes the issue with the broken user test.  Details in the commit msg.  

Side note: Since we were using lodash's `omit` to get rid of more fields (3) than we were keeping (2 - `password` and `email`), we may want to use `pick` to specify the fields we want, rather than `omit`... just a thought. 

Goodnight 😜

**Pull request merged**
